### ISSUE TITLE
zope.interface apparently breaks modulegraph2?

### ISSUE THREAD

**Issue by Lord-Kamina** [ronaldoussoren/modulegraph2#30]
Hi.
I am trying to use the master branch of py2app to make a package, but was getting an error:

```bash
python3.11 -m modulegraph2 -s /opt/deluge/deluge/ui/ui_entry.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/__main__.py", line 324, in <module>
    main(sys.argv[1:])
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/__main__.py", line 319, in main
    mg = make_graph(args)
         ^^^^^^^^^^^^^^^^
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/__main__.py", line 255, in make_graph
    mg.add_script(name)
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/_modulegraph.py", line 171, in add_script
    self._run_stack()
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/_modulegraph.py", line 366, in _run_stack
    func(*args)
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/_modulegraph.py", line 790, in _process_import
    node = self._find_or_load_module(importing_module, absolute_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/_modulegraph.py", line 688, in _find_or_load_module
    parent_node = self._find_or_load_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/_modulegraph.py", line 704, in _find_or_load_module
    node = self._load_module(importing_module, module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/_modulegraph.py", line 530, in _load_module
    node, imports = node_for_spec(spec, sys.path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Home/Library/Python/3.11/lib/python/site-packages/modulegraph2/_graphbuilder.py", line 239, in node_for_spec
    assert filename is not None
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
```
I put it through pdb to try and find what the issue is, and got this:

```bash
-> assert filename is not None
(Pdb) locals()
{'spec': ModuleSpec(name='zope', loader=<_frozen_importlib_external.NamespaceLoader object at 0x109044810>, submodule_search_locations=_NamespacePath(['/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zope'])), 'path': ['/opt/deluge', '/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11', '/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload', '/Users/Home/Library/Python/3.11/lib/python/site-packages', '/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages'], 'loader': <_frozen_importlib_external.NamespaceLoader object at 0x109044810>, 'inspect_loader': <_frozen_importlib_external.NamespaceLoader object at 0x109044810>, 'node_type': None, 'filename': None, 'source_code': ''}
```
I wanted to be sure that this was in fact the issue, so I did:

```python3
#!/usr/bin/env python3
import zope.interface
```

And put that through modulegraph2, which results in the exact same error.
I believe the issue is that for some reason, `source_code` is `''` instead of being `None`

**Comment by Lord-Kamina** [comment]
Ok so, what is happening is that modulegraph2 is assuming that `zope.interface` is an actual module inside package `zope`, so at some point it tries to `get_source` on zope and python returns an empty string  because it's essentially a namespace.

I believe the solution would be either:
- Account for the possibility that `get_source` can return ''
- Add some logic when processing parent packages to detect when something is just a namespace, so get_source isn't called at all.

The former options sounds much simpler, but I'm not sure which solution is really a better one.

**Comment by Lord-Kamina** [comment]
Ignore me, didn't notice a fix was already committed.
